menus:
    inicio: 
        title: menu.inicio
        route: home
        icon: home
    cadastro: 
        title: menu.cadastro.cadastro
        route: false
        icon: th
        children: 
            cadastro_usuario: 
                title: menu.cadastro.usuario
                route: usuario
                branches:
                    - {name: fos_user_registration_register, action: route.new}
            cadastro_cliente: 
                title: menu.cadastro.cliente
                route: pessoa
            cadastro_estado: 
                title : menu.cadastro.estado
                route : estado
            cadastro_cidade: 
                title : menu.cadastro.cidade
                route : cidade
    #imports will be replaced by the indicated resources
    #imports:
    #   - {resource: "cadastros.yml"}
